name: setting up node
on: push
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing bats
        run: npm install bats
      - name: Version of bats
        run: bats -v
      - name: Running a file
        run: node index.js
